image: node:8.15.1

variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/app

services:
  - name: cypress/browsers:chrome65-ff57

job:
  before_script:
    # only install meteor if bin isn't found
    - command -v meteor >/dev/null 2>&1 || curl https://install.meteor.com | /bin/sh
    # install npm packages
    - meteor npm ci

  script:
    - meteor npm run test:blackbox:headless
